name: Build and Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Or whatever branch you're deploying from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 'Build and Deploy to Azure Static Web Apps'
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        app_location: "/"   # This should point to the directory with your app's files
        output_location: "/"
